### ISSUE TITLE
Do so

### ISSUE THREAD

**Issue by SuperAdam47** [narapons/EconomyLand#1]
![48390395_505328893289413_4864904577096351744_n](https://user-images.githubusercontent.com/16169771/50373390-906e9680-05ef-11e9-828f-0f9c47efe63d.png)

![48413582_275034076491946_1634279706608009216_n](https://user-images.githubusercontent.com/16169771/50373391-92d0f080-05ef-11e9-9ae8-0eba2ff41105.png)

**Comment by narapons** [comment]
What happened? 
I can not understand that image

**Comment by SuperAdam47** [comment]
I say that if you have signs showing who the houses belong to and you write / land offer <price> and click on the sign of your house, you can sell the house.

**Comment by narapons** [comment]
sorry.
I can't it.
Bacause this plugin isn’t for doing it.
